name: Test SSH Connection

on:
  workflow_dispatch: # Solo manual

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "=== Conexión exitosa ==="
          whoami
          pwd
          ls -la